---

- name: starts nginx-rtmp
  systemd:
    enabled: yes
    state: started
    name: nginx-rtmp
    daemon_reload: yes

- name: reloads nginx-rtmp
  systemd:
    state: restarted
    name: nginx-rtmp
