---

- name: enables nginx-rtmp
  systemd:
    enabled: yes
    name: nginx-rtmp
    daemon_reload: yes

- name: restarts nginx-rtmp
  systemd:
    state: restarted
    name: nginx-rtmp

- name: enables nginx
  systemd:
    enabled: yes
    name: nginx
    daemon_reload: yes

- name: restarts nginx
  systemd:
    state: restarted
    name: nginx
