- name: installs golang version fact
  copy:
    src: golang-version.fact
    dest: /etc/ansible/facts.d/fort-golang-version.fact
    mode: '0755'
    owner: root
    group: root
  register: custom_fact_installed

- name: reloads facts
  setup:
  when: custom_fact_installed.changed == True

- name: installs desired go version
  block:
  - name: removes previous go
    file:
      name: /usr/local/go
      state: absent

  - name: downloads correct golang version
    get_url:
      url: https://go.dev/dl/go{{golang_version}}.linux-amd64.tar.gz
      dest: /tmp/go{{golang_version}}.linux-amd64.tar.gz

  - name: unpacks golang binaries to
    unarchive:
      src: /tmp/go{{golang_version}}.linux-amd64.tar.gz
      remote_src: yes
      dest: /usr/local

  - name: makes golang available to all users
    template:
      src: 99-golang.sh
      dest: /etc/profile.d/99-golang.sh

  when:  ansible_local['fort-golang-version']['golang_version'] != golang_version
