- name: installs golang version fact
  copy:
    src: golang-version.fact
    dest: /etc/ansible/facts.d/fort-0001-golang-version.fact
    mode: '0755'
    owner: root
    group: root

- name: installs desired go version
  block:
  - name: removes previous go
    file:
      name: /usr/local/go
      state: absent

  - name: downloads correct golang version
    get_url:
      url: https://dl.google.com/go/go{{golang_version}}.linux-amd64.tar.gz
      dest: /tmp/go{{golang_version}}.linux-amd64.tar.gz
    delegate_to: 127.0.0.1
    run_once: true

  - name: unpacks golang binaries to
    unarchive:
      src: /tmp/go{{golang_version}}.linux-amd64.tar.gz
      dest: /usr/local

  - name: makes golang available to all users
    template:
      src: 99-golang.sh
      dest: /etc/profile.d/99-golang.sh

  when:  ansible_local['fort-0001-golang-version'] is not defined or ansible_local['fort-0001-golang-version']['golang_version'] != golang_version
