---
- name: installs target kernel
  apt:
    name: ["linux-image-{{ kernel_version }}","linux-headers-{{ kernel_version }}", "linux-tools-{{ kernel_version }}"]
    state: present
  register: kernel_installed

- name: sets grubs default options
  template:
    src: grub.j2
    dest: /etc/default/grub
  register: grub_modified

- name: sets default user and reboot
  block:
    - name: updates grub first
      command: update-grub

    - name: sets default grub entry
      shell: |
        MENU=$(grep submenu /boot/grub/grub.cfg | cut -d "'" -f 4)
        SUBMENU=$(grep -E 'menuentry.*{{ kernel_version }}' /boot/grub/grub.cfg | head -n 1 | cut -d "'" -f 4)
        grub-set-default "$MENU>$SUBMENU"

    - name: updates grub second
      command: update-grub

    - name: reboots computer
      reboot:

  when:  kernel_installed.changed == True or grub_modified.changed == True
