---
- name: installs a recent kernel to fix graphics issues
  block:
    - name: allows snapshots
      copy:
        src: 99-allow-snapshot
        dest: /etc/apt/apt.conf.d/99-allow-snapshot

    - name: installs backports-snapshot
      apt_repository:
        repo: deb http://snapshot.debian.org/archive/debian/20190501T084202Z {{ ansible_distribution_release }}-backports main
        state: present
        filename: backports
        update_cache: yes

    - name: installs target kernel
      apt:
        name: ['linux-image-4.19.0-0.bpo.4-amd64','linux-headers-4.19.0-0.bpo.4-amd64']
        state: present
        default_release: stretch-backports
      notify: reboots machine
