---

## This playbook deploys the leto (tracking software) stack of the FORmicidae Tracker

- hosts: vision_masters,vision_slaves
  roles:
    - local-ntp
    - vncserver
    - leto
    - coaxlink-firmware
