---
- name: installs custom facts
  copy:
    src: fort-coaxlink-firmware.fact
    dest: /etc/ansible/facts.d/fort-coaxlink-firmware.fact
    owner: root
    group: root
    mode: '0755'
  register: custom_fact_installed

- name: reloads facts
  setup:
  when: custom_fact_installed.changed == True

- name: updates firmware
  block:
  - name: upload firmware
    shell: |
      coaxlink-firmware install {{coaxlink_firmware_variant}} --card=0

  # the later is needed as otherwise the new firmware is not loaded
  # with a simple reboot.
  - name: reboots machine with delay
    shell: |
      echo 0 > /sys/class/rtc/rtc0/wakealarm
      echo `date '+%s' -d '+4 minutes'` > /sys/class/rtc/rtc0/wakealarm
      shutdown +1 "Euresys firmware update"

  when: ansible_local['fort-coaxlink-firmware']['firmware-version'] != coaxlink_firmware_version or ansible_local['fort-coaxlink-firmware']['firmware-variant'] != coaxlink_firmware_variant
