---

- name: installs curl and mailutils
  apt:
    name: ['curl','mailutils']
    state: present

- name: installs private script
  template:
    src: greet-on-slack.sh.j2
    dest: /usr/local/bin/greet-on-slack.sh
    mode: 0700
    owner: root
    group: root

- name: installs service
  copy:
    src: greet-on-slack.service
    dest: /etc/systemd/system/greet-on-slack.service
    owner: root
    group: root

- name: enables service
  service:
    name: greet-on-slack
    enabled: true
