---

- name: installs nginx
  apt:
    name: nginx
    state: present

- name: sets nginx configuration
  template:
    src: nginx_default.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

- name: enables and starts nginx
  service:
    name: nginx
    state: started
    enabled: true
