---
- name: adds default user
  shell: |
    if id -u fort-user > /dev/null
    then
    	exit 0
    fi
    echo -ne "123456\n123456\nDefault user for the FORmicidae Tracker\n\n\n\n\n" | adduser fort-user
    echo "fort-user:123456" | /usr/sbin/chpasswd

- name: sets user as default logged in user
  copy:
    src: daemon.conf
    dest: /etc/gdm3/daemon.conf

- name: installs vncserver
  apt:
    name: x11vnc
    state: present

- name: makes users systemd config dir
  file:
    name: /home/fort-user/.config/systemd/user/default.target.wants
    state: directory
    owner: fort-user
    group: fort-user
    mode: '0755'

- name: adds user systemd service
  copy:
    src: vncserver.service
    dest: /home/fort-user/.config/systemd/user/vncserver.service
    owner: fort-user
    group: fort-user
    mode: '0644'

- name: installs user service
  file:
    src: /home/fort-user/.config/systemd/user/vncserver.service
    dest: /home/fort-user/.config/systemd/user/default.target.wants/vncserver.service
    state: link
    owner: fort-user
    group: fort-user
    mode: '0644'
  notify: reboots machine
