---
- name: adds default user
  shell: |
    if id -u fort-user > /dev/null
    then
    	exit 0
    fi
    echo -ne "123456\n123456\nDefault user for the FORmicidae Tracker\n\n\n\n\n" | adduser fort-user
    echo "fort-user:123456" | /usr/sbin/chpasswd

- name: sets user as default logged in user
  copy:
    src: daemon.conf
    dest: /etc/gdm3/custom.conf

- name: installs vino server
  apt:
    name: vino
    state: present

- name: setups vinoserver
  become_user: fort-user
  shell: |
    set -e
    export DISPLAY=:0
    gsettings set org.gnome.Vino prompt-enabled false
    gsettings set org.gnome.Vino require-encryption false
    eths=$(nmcli -t -f uuid,type c s --active | grep 802 | awk -F  ":" '{ print "'\''" $1 "'\''" }' | paste -s -d, -)
    gsettings set org.gnome.settings-daemon.plugins.sharing.service:/org/gnome/settings-daemon/plugins/sharing/vino-server/ enabled-connections "[ $eths ]"

- name: tests server is running
  shell: pgrep vino 1>/dev/null || echo notok
  register: vino_pid

- name: reboots machine to start vino
  reboot:
  when: 'vino_pid.stdout == "notok"'
