---
- name: adds default user
  shell: |
    if id -u fort-user > /dev/null
    then
    	exit 0
    fi
    echo -ne "123456\n123456\nDefault user for the FORmicidae Tracker\n\n\n\n\n" | adduser fort-user
    echo "fort-user:123456" | /usr/sbin/chpasswd

- name: sets user as default logged in user
  copy:
    src: daemon.conf
    dest: /etc/gdm3/custom.conf
  register: default_user_set

- name: reboots system
  reboot:
  when: default_user_set.changed

- name: removes vino server
  apt:
    name: vino
    state: absent

- name: installs libsecret
  apt:
    name: libsecret-tools
    state: present

- name: activate VNC/RDP Server
  become_user: fort-user
  shell: |
    set -e
    export DISPLAY=:0

    gsettings set org.gnome.desktop.remote-desktop.rdp enable true
    gsettings set org.gnome.desktop.remote-desktop.vnc enable true
    gsettings set org.gnome.desktop.remote-desktop.vnc auth-method "'password'"


- name: deactivate idle lock screen
  become_user: fort-user
  shell: |
    set -e
    export DISPLAY=:0

    gsettings set org.gnome.desktop.session idle-delay 0
