---
- name: removes vino server
  apt:
    name: vino
    state: absent

- name: installs libsecret
  apt:
    name: libsecret-tools
    state: present

- name: activate VNC/RDP Server
  become_user: fort-user
  shell: |
    set -e
    export DISPLAY=:0

    gsettings set org.gnome.desktop.remote-desktop.rdp enable true
    gsettings set org.gnome.desktop.remote-desktop.vnc enable true
    gsettings set org.gnome.desktop.remote-desktop.vnc auth-method "'password'"


- name: deactivate idle lock screen
  become_user: fort-user
  shell: |
    set -e
    export DISPLAY=:0

    gsettings set org.gnome.desktop.session idle-delay 0
