---
- name: adds default user
  shell: |
    if [ id -u name ]
    then
    	exit 0
    fi
    echo -ne "123456\n123456\nDefault user for the FORmicidae Tracker\n\n\n\n\n" | adduser fort-user
    echo "fort-user:123456" | /usr/sbin/chpasswd

- name: sets user as default logged in user
  copy:
    src: daemon.conf
    dest: /etc/gdm3/daemon.conf

- name: installs vncserver
  apt:
    name: x11vnc
    state: present

- name: makes users systemd config dir
  file:
    name: /home/fort-user/.config/systemd/user/default.target.wants
    state: directory
    owner: fort-user
    group: fort-user
    mode: '0755'

- name: adds user systemd service
  copy:
    src: vncserver.service
    dest: /home/fort-user/.config/systemd/user/vncserver.service
    owner: fort-user
    group: fort-user
    mode: '0644'

- name: installs a recent kernel to fix graphics issues
  block:
    - name: allows snapshots
      copy:
        src: 99-allow-snapshot
        dest: /etc/apt/apt.conf.d/99-allow-snapshot

    - name: installs backports-snapshot
      apt_repository:
        repo: deb http://snapshot.debian.org/archive/debian/20180425T160425Z {{ ansible_distribution_release }}-backports main
        state: present
        filename: backports
        update_cache: yes

    - name: installs target kernel
      apt:
        name: ['linux-image-4.15.0-0.bpo.2-amd64','linux-headers-4.15.0-0.bpo.2-amd64']
        state: present
        default_release: stretch-backports
      notify: reboots machine


- name: installs user service
  file:
    src: /home/fort-user/.config/systemd/user/vncserver.service
    dest: /home/fort-user/.config/systemd/user/default.target.wants/vncserver.service
    state: link
    owner: fort-user
    group: fort-user
    mode: '0644'
  notify: reboots machine
