---
- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: enable leto service
  systemd:
    name: leto
    enabled: yes
    daemon_reload: yes

- name: restart leto service
  systemd:
    name: leto
    state: restarted
