- name : disables systemd timesync
  command: timedatectl set-ntp off

- name : installs ntp
  apt:
    name: ntp
    state: present

- name: configure local ntp server
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restarts ntpd daemon
