---

- name: reload exports
  command: /usr/sbin/exportfs -a
  listen: "restarts nfs"

- name: restart nfs service
  service:
    name: nfs-kernel-server
    state: restarted
  listen: "restarts nfs"
