---
- name: installs custom fact
  copy:
    src: fort-0003-olympus-version.fact
    dest: /etc/ansible/facts.d/fort-0003-olympus-version.fact
    mode: '0755'


- name: installs olympus
  block:
  - name: adds backports
    apt_repository:
      repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
      state: present
      filename: backports
      update_cache: yes

  - name: installs node
    apt:
      name: ['nodejs', 'git']
      default_release: stretch-backports
      state: present

  - name: installs yarn and angular cli
    npm:
      name: "{{ item }}"
      state: present
      global: yes
    with_items:
      - yarn
      - "@angular/cli"

  - name: creates system user olympus
    user:
      name: olympus
      system: yes
      home: /home/olympus
      state: present

  - name: downloads olympus sources
    git:
      repo: 'https://github.com/formicidae-tracker/olympus.git'
      dest: /home/olympus/olympus
      force: yes
      version: "{{olympus_version}}"

  - name: builds olympus
    shell: |
      cd /home/olympus/olympus
      /usr/local/go/bin/go build
      cd webapp
      yarn install
      yarn build --prod



  when:  ansible_local['fort-0003-olympus-version'] is not defined or ansible_local['fort-0003-olympus-version']['olympus-version'] != olympus_version

- name: installs rsyslog handler
  template:
    src: syslog.conf.j2
    dest: /etc/rsyslog.d/olympus.conf
  notify: restarts rsyslog

- name: installs olympus service
  template:
    src: olympus.service.j2
    dest: /etc/systemd/system/olympus.service
  notify:
    - enables olympus service
    - restarts olympus service
