---
- name: installs custom fact
  copy:
    src: fort-olympus-version.fact
    dest: /etc/ansible/facts.d/fort-olympus-version.fact
    mode: '0755'
  register: custom_fact_installed

- name: reloads facts
  setup:
  when: custom_fact_installed.changed == True

- name: creates system user olympus
  user:
    name: olympus
    system: yes
    home: /home/olympus
    state: present

- name: removes backports
  apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
      state: absent
      filename: backports
      update_cache: yes

- name: installs dependencies
  apt:
    name: git
    state: present

- name: removes system nodejs
  apt:
    name: nodejs
    state: absent

- name: installs olympus
  become: yes
  become_user: olympus
  block:

  - name: installs nvm
    shell: >
        curl https://raw.githubusercontent.com/creationix/nvm/v0.37.2/install.sh | sh
        creates=/home/{{ansible_user_id}}/.nvm/nvm.sh

  - name: installs node and set version
    shell: >
      /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 14 && nvm use --default 14
      creates=/home/{{ansible_user_id}}/.nvm/alias

  - name: downloads olympus sources
    git:
      repo: 'https://github.com/formicidae-tracker/olympus.git'
      dest: /home/olympus/olympus
      force: yes
      version: "{{olympus_version}}"

  - name: builds olympus
    shell: |
      source ~/.nvm/nvm.sh
      cd /home/olympus/olympus
      export PATH=$PATH:/usr/local/go/bin
      make clean all

  when: ansible_local['fort-olympus-version']['olympus-version'] != olympus_version

- name: installs rsyslog handler
  template:
    src: syslog.conf.j2
    dest: /etc/rsyslog.d/olympus.conf
  notify: restart rsyslog

- name: installs olympus service
  template:
    src: olympus.service.j2
    dest: /etc/systemd/system/olympus.service
  notify:
    - restart olympus service

- name: installs olympus secrets
  template:
    src: olympus.env.j2
    dest: /etc/default/olympus.env
    mode: '0700'
  notify:
    - restart olympus service

- name: starts olympus service
  systemd:
    name: olympus
    state: started
    enabled: true
