---
- name: removes distribution nginx
  apt:
    name: nginx
    state: absent

- name: installs custom fact
  copy:
    src: fort-0002-nginx-rtmp-version.fact
    dest: /etc/ansible/facts.d/fort-0002-nginx-rtmp-version.fact
    owner: root
    group: root
    mode: '0755'

- name: installs runtime dependencies
  apt:
    name: ['ffmpeg']
    state: present

- name: installs nginx with rtmp module
  block:
  - name: install nginx dependencies
    apt:
      name : ['build-essential','libpcre3-dev','libssl-dev','zlib1g-dev']
      update_cache: true
      state: present

  - name: cleans previous nginx installation
    file:
      name: /usr/local/nginx
      state: absent

  - name: downloads nginx sources
    get_url:
      url: https://nginx.org/download/nginx-{{nginx_version}}.tar.gz
      dest: /tmp/nginx-{{nginx_version}}.tar.gz
    delegate_to: 127.0.0.1
    run_once: true

  - name: downloads nginx-rtmnp-module sources
    get_url:
      url: https://github.com/arut/nginx-rtmp-module/archive/v{{nginx_rtmp_version}}.tar.gz
      dest: /tmp/nginx-rtmp-module-{{nginx_rtmp_version}}.tar.gz
    delegate_to: 127.0.0.1
    run_once: true

  - name: extracts nginx sources
    unarchive:
      src: /tmp/nginx-{{nginx_version}}.tar.gz
      dest: /tmp

  - name: extracts nginx-rtmp sources
    unarchive:
      src: /tmp/nginx-rtmp-module-{{nginx_rtmp_version}}.tar.gz
      dest: /tmp

  - name: builds and installs nginx
    shell: |
      cd /tmp
      cd nginx-{{nginx_version}}
      ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module-{{nginx_rtmp_version}}
      make -j 4
      make install

  - name: adds www-data user
    user:
      system: yes
      name: www-data
      home: /var/www
      create_home: yes
      state: present

  - name: creates missing directories
    file:
      path: "{{ item }}"
      state: directory
      owner: www-data
    with_items:
      - /usr/local/nginx/conf/sites-enabled/
      - /usr/local/nginx/conf/sites-available/
      - /usr/local/nginx/conf/conf.d
      - /var/log/nginx

  - name: sets nginx configuration
    template:
      src: nginx.conf.j2
      dest: /usr/local/nginx/conf/nginx.conf

  - name: installs systemd service for nginx
    template:
      src: nginx.service.j2
      dest: /etc/systemd/system/nginx-rtmp.service
    notify: enables nginx-rtmp

  - name: starts nginx service
    systemd:
      name: nginx-rtmp
      state: started

  when:  ansible_local['fort-0002-nginx-rtmp-version'] is not defined or ansible_local['fort-0002-nginx-rtmp-version']['nginx-version'] != nginx_version or ansible_local['fort-0002-nginx-rtmp-version']['nginx-rtmp-version'] != nginx_rtmp_version

- name: Sets nginx configuration
  template:
    src: nginx.conf.j2
    dest: /usr/local/nginx/conf/nginx.conf
  notify: restarts nginx-rtmp

- name: Ensures tmpfs mount point is present
  file:
    path: /var/www/olympus
    state: directory
    group: www-data
    owner: www-data
    mode: 0755

- name: Ensures tmpfs folder for streaming is present
  mount:
    path: /var/www/olympus
    fstype: tmpfs
    opts: size=512m
    src: tmpfs
    state: present
  notify: restarts nginx-rtmp

# - name : Ensures
#   file:
#     path: "{{ item }}"
#     state: directory
#     mode: 0755
#     owner: www-data
#     group: www-data
#   with_items:
#     - /var/www/olympus/hls
#     - /var/www/olympus/keyframes


- name: sets default server configuration
  template:
    src: default.j2
    dest: /usr/local/nginx/conf/sites-available/default
  notify: restarts nginx-rtmp

- name: enables default server
  file:
    src: /usr/local/nginx/conf/sites-available/default
    dest: /usr/local/nginx/conf/sites-enabled/default
    state: link
  notify: restarts nginx-rtmp
