---
- name: installs distribution nginx
  apt:
    name: nginx
    state: present

- name: installs custom fact
  copy:
    src: fort-nginx-rtmp-version.fact
    dest: /etc/ansible/facts.d/fort-nginx-rtmp-version.fact
    owner: root
    group: root
    mode: '0755'
  register: custom_fact_installed

- name: reloads facts
  setup:
  when: custom_fact_installed.changed == True

- name: installs runtime dependencies
  apt:
    name: ['ffmpeg', 'python3-passlib', 'nfs-common']
    state: present

- name: installs nginx with rtmp module
  block:
  - name: install nginx dependencies
    apt:
      name : ['build-essential','libpcre3-dev','libssl-dev','zlib1g-dev']
      update_cache: true
      state: present

  - name: cleans previous nginx installation
    file:
      name: /usr/local/nginx
      state: absent

  - name: downloads nginx sources
    get_url:
      url: https://nginx.org/download/nginx-{{nginx_version}}.tar.gz
      dest: /tmp/nginx-{{nginx_version}}.tar.gz
    delegate_to: 127.0.0.1
    run_once: true

  - name: downloads nginx-rtmnp-module sources
    get_url:
      url: https://github.com/arut/nginx-rtmp-module/archive/v{{nginx_rtmp_version}}.tar.gz
      dest: /tmp/nginx-rtmp-module-{{nginx_rtmp_version}}.tar.gz
    delegate_to: 127.0.0.1
    run_once: true

  - name: extracts nginx sources
    unarchive:
      src: /tmp/nginx-{{nginx_version}}.tar.gz
      dest: /tmp

  - name: extracts nginx-rtmp sources
    unarchive:
      src: /tmp/nginx-rtmp-module-{{nginx_rtmp_version}}.tar.gz
      dest: /tmp

  - name: builds and installs nginx
    shell: |
      cd /tmp
      cd nginx-{{nginx_version}}
      ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module-{{nginx_rtmp_version}}
      make -j 4
      make install

  - name: adds www-data user
    user:
      system: yes
      name: www-data
      home: /var/www
      create_home: yes
      state: present

  - name: creates missing directories
    file:
      path: "{{ item }}"
      state: directory
      owner: www-data
    with_items:
      - /usr/local/nginx/conf/sites-enabled/
      - /usr/local/nginx/conf/sites-available/
      - /usr/local/nginx/conf/conf.d
      - /var/log/nginx

  - name: sets nginx configuration
    template:
      src: nginx.conf.j2
      dest: /usr/local/nginx/conf/nginx.conf

  - name: installs systemd service for nginx
    template:
      src: nginx.service.j2
      dest: /etc/systemd/system/nginx-rtmp.service

  when:  ansible_local['fort-nginx-rtmp-version']['nginx-version'] != nginx_version or ansible_local['fort-nginx-rtmp-version']['nginx-rtmp-version'] != nginx_rtmp_version

- name: ensures tmpfs mount point is present
  file:
    path: /var/www/olympus
    state: directory
    group: www-data
    owner: www-data
    mode: 0755

- name: ensures tmpfs folder for streaming is present
  mount:
    path: /var/www/olympus
    fstype: tmpfs
    opts: "size={{tmpfs_size}}"
    src: tmpfs
    state: mounted
  notify: restart nginx-rtmp

- name : creates nodes directory
  file:
    path: /srv/nodes/{{ item | regex_replace('\.local') }}
    state: directory
  with_items: "{{ groups['vision_masters'] + groups['vision_slaves'] | unique }}"

- name: sets basic auth
  htpasswd:
    path: /etc/nginx/htpasswd
    name: fort-user
    password: "{{ basic_auth_password }}"
    owner: root
    group: www-data
    mode: 0640
  notify: restart nginx

- name: sets nginx-rtmp configuration
  template:
    src: nginx.conf.j2
    dest: /usr/local/nginx/conf/nginx.conf
  notify: restart nginx-rtmp

- name: sets nginx configuration
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  vars:
    - nodes: "{{ groups['vision_masters'] + groups['vision_slaves'] | unique }}"
  notify: restart nginx

- name: enables default server in distribution nginx
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx

- name: disables default http server in nginx-rtmp
  file:
    name: /usr/local/nginx/conf/sites-enabled/default
    state: absent
  register: nginx_rtmp_default_disabled

- name: restarts nginx-rtmp
  service:
    name: nginx-rtmp
    daemon_reload: true
    state: restarted
  when: nginx_rtmp_default_disabled.changed == True

- name: enables and starts nginx-rtmp-service
  service:
    name: nginx-rtmp
    daemon_reload: true
    enabled: true
    state: started
