---
- name: installs mainline kernel scripts
  get_url:
    url: https://raw.githubusercontent.com/pimlie/ubuntu-mainline-kernel.sh/master/ubuntu-mainline-kernel.sh
    dest: /usr/local/bin/ubuntu-mainline-kernel.sh
    owner: root
    mode: '0755'

- name: removes old fixed kernel
  file:
    name: /etc/default/grub.d/fixed-kernel.cfg
    state: absent

- name: ensure use saved grub entry
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_DEFAULT="
    line: "GRUB_DEFAULT=saved"
  notify: update grub

- name: sets default kernel boot
  shell: |
    if grub-editenv list | grep "saved_entry=Advanced options for Ubuntu>Ubuntu, with Linux {{ target_linux_kernel }}" 1>/dev/null
    then
        exit 0
    fi

    subentry=$(grep menuentry /boot/grub/grub.cfg | grep {{ target_linux_kernel }} | head -n 1 | cut -d "'" -f 2)
    grub-set-default "Advanced options for Ubuntu>$subentry" 1>/dev/null
    update-grub 1>/dev/null

    echo "kernel_installed"
  register: kernel_installation

- name: reboots computer
  reboot:
  when: kernel_installation.stdout == "kernel_installed"
