---

- hosts: vision_masters, vision_slaves
  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: true
  tasks:
    - name: removes drivers
      shell: |
        set +e
        dkms remove egrabber/14.0.1.167 --all
        dkms remove memento/15.0.0.140 --all
        rm -Rf /usr/local/lib/libfort-hermes*
        dirs="/opt/euresys/egrabber-linux-x86_64-14.0.1.167/ /opt/euresys/memento-linux-x86_64-15.0.0.140/"
        for d in $dirs
        do
          if [ -e $d ]
          then
            sed -i 's/confirmRemoveProduct//' $d/uninstall.sh
            $d/uninstall.sh
          fi
        done

    - name: removes old sources
      file:
        name: "{{item}}"
        state: absent
      with_items:
        - /usr/src/egrabber-14.0.1.167
        - /usr/src/memento-15.0.0.140
        - /usr/local/src/euresys
        - /usr/local/bin/install_euresys_modules.sh
