---
- name: installs custom fact
  copy:
    src: fort-zeus-version.fact
    dest: /etc/ansible/facts.d/fort-zeus-version.fact
    mode: '0755'
  register: custom_fact_installed

- name: reloads facts
  setup:
  when: custom_fact_installed.changed == True

- name: installs zeus service
  template:
    src: zeus.service.j2
    dest: /etc/systemd/system/zeus.service

- name: installs logrotate configuration
  copy:
    src: logrotate.conf
    dest: /etc/logrotate.d/zeus

- name: installs rsyslog handler
  copy:
    src: syslog.conf
    dest: /etc/rsyslog.d/zeus.conf
  notify: restart rsyslog

- name: installs zeus config
  template:
    src: default-zeus.yml.j2
    dest: /etc/default/zeus.yml
  notify: restart zeus

- name: installs zeus and utilities
  block:
  - name: ensures make is installed
    apt:
      name: [ 'build-essential', 'git' ]
      state: present

  - name: downloads zeus sources
    git:
      repo: 'https://github.com/formicidae-tracker/zeus.git'
      dest: /usr/local/src/zeus
      force: yes
      version: "{{zeus_version}}"

  - name: builds zeus
    shell: |
      cd /usr/local/src/zeus
      export PATH=$PATH:/usr/local/go/bin
      make clean all
      make install
    notify: restart zeus

  when:  ansible_local['fort-zeus-version']['zeus-version'] != zeus_version

- name: enables zeus
  systemd:
    name: zeus
    enabled: yes
    state: started
