---
- name: installs custom fact
  copy:
    src: fort-zeus-version.fact
    dest: /etc/ansible/facts.d/fort-zeus-version.fact
    mode: '0755'
  notify: reload facts

- name: installs zeus and utilities
  block:
  - name: ensures make is installed
    apt:
      name: [ 'build-essential', 'git' ]
      state: present

  - name: downloads zeus sources
    git:
      repo: 'https://github.com/formicidae-tracker/zeus.git'
      dest: /usr/local/src/zeus
      force: yes
      version: "{{zeus_version}}"

  - name: builds zeus
    shell: |
      cd /usr/local/src/zeus
      export PATH=$PATH:/usr/local/go/bin
      make
      make install

  when:  ansible_local['fort-zeus-version']['zeus-version'] != zeus_version
