
---

- name: installs leto runtime dependencies
  apt:
    name:
      - ffmpeg
    state: present
  notify: restart leto service


- name: ensures data dir is existing
  file:
    name: "{{leto_data_dir}}"
    state: directory
    mode: '0755'
    owner: fort-user
    group: fort-user

- name: installs rsyslog handler
  template:
    src: syslog.conf.j2
    dest: /etc/rsyslog.d/leto.conf
  notify: restart rsyslog

- name: installs logrotate configuration
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/leto

- name: installs leto default configuration
  template:
    src: leto.yml.j2
    dest: /etc/default/leto.yml

- name: removes legacy system leto service
  file:
    path: /etc/systemd/system/leto.service
    state: absent
  register: removed_legacy_service

- name: reloads system systemd
  systemd:
    daemon_reload: yes
  when: removed_legacy_service.changed

- name: installs leto service
  template:
    src: leto.service.j2
    dest: /etc/systemd/user/leto.service
  notify:
    - enable leto service
    - restart leto service
