- name: installs required packages
  apt:
    name: ['libprotobuf-dev' ]
    default_release: stretch-backports


- name: ensures destination dir
  file:
    name: /usr/local/fort/debs/
    state: directory

- name: copying debian packages
  copy:
    src: "{{item}}"
    dest: "/usr/local/fort/debs/{{item}}"
  with_items:
    - libapriltag3_{{apriltag_version}}_amd64.deb
    - libapriltag-dev_{{apriltag_version}}_amd64.deb
    - libfort-hermes-cpp0.1_{{hermes_version}}_amd64.deb
    - libfort-hermes-cpp-dev_{{hermes_version}}_amd64.deb
    - libfort-hermes0.1_{{hermes_version}}_amd64.deb
    - libfort-hermes-dev_{{hermes_version}}_amd64.deb
    - artemis_{{artemis_version}}_amd64.deb

- name: install packages
  command: "dpkg -i /usr/local/fort/debs/{{item}}"
  with_items:
    - libapriltag3_{{apriltag_version}}_amd64.deb
    - libapriltag-dev_{{apriltag_version}}_amd64.deb
    - libfort-hermes-cpp0.1_{{hermes_version}}_amd64.deb
    - libfort-hermes-cpp-dev_{{hermes_version}}_amd64.deb
    - libfort-hermes0.1_{{hermes_version}}_amd64.deb
    - libfort-hermes-dev_{{hermes_version}}_amd64.deb
    - artemis_{{artemis_version}}_amd64.deb
