---
- name: installs custom facts
  copy:
    src: fort-0006-leto-version.fact
    dest: /etc/ansible/facts.d/fort-0006-leto-version.fact
    mode: '0755'

- name: adds protobuf ppa
  apt_repository:
    repo: ppa:maarten-fonville/protobuf

- name: adds kitware repository key
  shell: |
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -

- name: adds kitware repository
  apt_repository:
    repo: deb https://apt.kitware.com/ubuntu/ bionic main
    state: present
    filename: kitware

- name: installs required packages
  apt:
    name: ['libprotobuf-dev',
    'git',
    'git-lfs',
    'cmake',
    'protobuf-compiler',
    'libgoogle-glog-dev',
    'libopencv-dev',
    'libopencv-imgproc-dev',
    'libopencv-highgui-dev',
    'libboost-system-dev',
    'libglfw3-dev',
    'libglew-dev',
    'libasio-dev',
    'libboost-dev',
    'libeigen3-dev',
    'libfontconfig1-dev',
    'libfreetype6-dev',
    'google-mock',
    'ffmpeg' ]
    state: latest

- name: installs artemis
  block:
  - name: downloads artemis sources
    git:
      name: https://github.com/formicidae-tracker/artemis.git
      dest: /usr/local/src/artemis
      version: "{{artemis_version}}"
      force: yes

  - name: compiles artemis
    shell: |
      set -e
      export PATH="$PATH:/usr/local/go/bin"
      cd /usr/local/src/artemis
      mkdir -p build
      cd build
      cmake ../ -DCMAKE_BUILD_TYPE=Release
      make
      make install
      rm -f /usr/local/lib/libapriltag.so
      rm -f /usr/local/lib/libapriltag.so.3
      rm -f /usr/local/lib/libapriltag.so.3.0.0
      ldconfig
    notify: restarts leto service

  when: ansible_local['fort-0006-leto-version'] is not defined or ansible_local['fort-0006-leto-version']['artemis-version'] != artemis_version



- name: installs leto from sources
  block:
    - name: download leto sources
      git:
        name: https://github.com/formicidae-tracker/leto.git
        dest: /usr/local/src/leto
        version: "{{ leto_version }}"
        force: yes

    - name: installs leto
      shell: |
        cd /usr/local/src/leto/leto
        /usr/local/go/bin/go build
        install leto /usr/local/bin
      notify: restarts leto service


  when: ansible_local['fort-0006-leto-version'] is not defined or ansible_local['fort-0006-leto-version']['leto-version'] != leto_version


- name: ensures data dir is existing
  file:
    name: "{{leto_data_dir}}"
    state: directory
    mode: '0755'
    owner: fort-user
    group: fort-user

- name: installs rsyslog handler
  template:
    src: syslog.conf.j2
    dest: /etc/rsyslog.d/leto.conf
  notify: restarts rsyslog

- name: installs logrotate configuration
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/leto

- name: installs leto service
  template:
    src: leto.service.j2
    dest: /etc/systemd/system/leto.service
  notify:
    - enables leto service
    - restarts leto service

- name: installs leto default configuration
  template:
    src: leto.yml.j2
    dest: /etc/default/leto.yml
