---
- name: installs custom facts
  copy:
    src: fort-leto-version.fact
    dest: /etc/ansible/facts.d/fort-leto-version.fact
    mode: '0755'
  register: custom_fact_installed

- name: reloads facts
  setup:
  when: custom_fact_installed.changed == True

- name: installs required packages
  apt:
    name: ['libprotobuf-dev',
    'git',
    'git-lfs',
    'cmake',
    'protobuf-compiler',
    'libgoogle-glog-dev',
    'libopencv-dev',
    'libopencv-imgproc-dev',
    'libopencv-highgui-dev',
    'libboost-system-dev',
    'libglfw3-dev',
    'libglew-dev',
    'libasio-dev',
    'libboost-dev',
    'libeigen3-dev',
    'libfontconfig1-dev',
    'libfreetype6-dev',
    'google-mock',
    'ffmpeg' ]
    state: present

- name: installs artemis
  block:
  - name: downloads artemis sources
    git:
      name: https://github.com/formicidae-tracker/artemis.git
      dest: /usr/local/src/artemis
      version: "{{artemis_version}}"
      force: yes

  - name: compiles artemis
    shell: |
      set -e
      cd /usr/local/src/artemis
      rm -f /usr/local/lib/libfort-hermes*
      export PATH=$PATH:/usr/local/go/bin
      mkdir -p build
      cd build
      rm -f CMakeCache.txt
      cmake ../ -DCMAKE_BUILD_TYPE=Release
      make -j 11
      make install
      rm -f /usr/local/lib/libapriltag.so
      rm -f /usr/local/lib/libapriltag.so.3
      rm -f /usr/local/lib/libapriltag.so.3.0.0
      ldconfig
    notify: restart leto service

  when: ansible_local['fort-leto-version']['artemis-version'] != artemis_version

- name: installs leto from sources
  block:
    - name: download leto sources
      git:
        name: https://github.com/formicidae-tracker/leto.git
        dest: /usr/local/src/leto
        refspec: dev/next
        version: "{{ leto_version }}"
        force: yes

    - name: installs leto
      shell: |
        cd /usr/local/src/leto
        export PATH=/root/go/bin:$PATH:/usr/local/go/bin

        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
        go install github.com/golang/mock/mockgen@v1.6.0

        make clean all
        install leto/leto /usr/local/bin
      notify: restart leto service

  when: ansible_local['fort-leto-version']['leto-version'] != leto_version


- name: ensures data dir is existing
  file:
    name: "{{leto_data_dir}}"
    state: directory
    mode: '0755'
    owner: fort-user
    group: fort-user

- name: installs rsyslog handler
  template:
    src: syslog.conf.j2
    dest: /etc/rsyslog.d/leto.conf
  notify: restart rsyslog

- name: installs logrotate configuration
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/leto

- name: installs leto service
  template:
    src: leto.service.j2
    dest: /etc/systemd/system/leto.service
  notify:
    - enable leto service
    - restart leto service

- name: installs leto default configuration
  template:
    src: leto.yml.j2
    dest: /etc/default/leto.yml
