---
- name: installs custom facts
  copy:
    src: fort-leto-version.fact
    dest: /etc/ansible/facts.d/fort-leto-version.fact
    mode: '0755'
  register: custom_fact_installed

- name: reloads facts
  setup:
  when: custom_fact_installed.changed == True

- name: installs artemis
  import_tasks: build_and_install_artemis.yml
  when: ansible_local['fort-leto-version']['artemis-version'] != artemis_version
  notify: restart leto service

- name: install leto
  import_tasks: build_and_install_leto.yml
  when: ansible_local['fort-leto-version']['leto-version'] != leto_version
  notify: restart leto service

- name: configure leto service
  import_tasks: configure_leto.yml

