---
- name: installs custom facts
  copy:
    src: fort-0006-leto-version.fact
    dest: /etc/ansible/facts.d/fort-0006-leto-version.fact
    mode: '0755'

- name: adds protobuf ppa
  apt_repository:
    repo: ppa:maarten-fonville/protobuf

- name: installs required packages
  apt:
    name: ['libprotobuf-dev', 'git', 'git-lfs', 'cmake', 'protobuf-compiler', 'libgoogle-glog-dev', 'libopencv-dev', 'libopencv-imgproc-dev', 'libopencv-highgui-dev', 'libasio-dev', 'libboost-dev', 'libeigen3-dev', 'google-mock', 'ffmpeg' ]

- name: installs apriltag
  block:
  - name: downloads apriltag source
    git:
      name: https://github.com/AprilRobotics/apriltag.git
      dest: /usr/local/src/apriltag
      version: "{{ apriltag_version }}"
      force: yes

  - name: installs apriltags
    shell: |
      cd /usr/local/src/apriltag
      sed -i 's/0\.10\.0/3.0.0/' apriltag.pc.in
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Release ../
      make
      make install
      ldconfig

  when: ansible_local['fort-0006-leto-version'] is not defined or ansible_local['fort-0006-leto-version']['apriltag-version'] != apriltag_version

- name: installs hermes
  block:
  - name: downloads hermes sources
    git:
      name: https://github.com/formicidae-tracker/hermes.git
      dest: /usr/local/src/hermes
      version: "{{hermes_version}}"
      force: yes

  - name: installs hermes
    shell: |
      cd /usr/local/src/hermes
      mkdir -p build
      cd build
      cmake ../ -DCMAKE_BUILD_TYPE=Release
      make
      make install
      ldconfig

  when: ansible_local['fort-0006-leto-version'] is not defined or ansible_local['fort-0006-leto-version']['hermes-version'] != hermes_version

- name: installs artemis
  block:
  - name: downloads artemis sources
    git:
      name: https://github.com/formicidae-tracker/artemis.git
      dest: /usr/local/src/artemis
      version: "{{artemis_version}}"
      force: yes

  - name: compiles artemis
    shell: |
      cd /usr/local/src/artemis
      mkdir -p build
      cd build
      cmake ../ -DCMAKE_BUILD_TYPE=Release
      make
      make install

  when: ansible_local['fort-0006-leto-version'] is not defined or ansible_local['fort-0006-leto-version']['artemis-version'] != artemis_version

- name: installs leto from sources
  block:
    - name: download leto sources
      git:
        name: https://github.com/formicidae-tracker/leto.git
        dest: /usr/local/src/leto
        version: "{{ leto_version }}"
        force: yes

    - name: installs leto
      shell: |
        cd /usr/local/src/leto/leto
        /usr/local/go/bin/go build
        install leto /usr/local/bin
      notify: restarts leto service


  when: ansible_local['fort-0006-leto-version'] is not defined or ansible_local['fort-0006-leto-version']['leto-version'] != leto_version


- name: ensures data dir is existing
  file:
    name: "{{leto_data_dir}}"
    state: directory
    mode: '0755'
    owner: fort-user
    group: fort-user

- name: installs rsyslog handler
  template:
    src: syslog.conf.j2
    dest: /etc/rsyslog.d/leto.conf
  notify: restarts rsyslog

- name: installs logrotate configuration
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/leto

- name: installs leto service
  template:
    src: leto.service.j2
    dest: /etc/systemd/system/leto.service
  notify:
    - enables leto service
    - restarts leto service

- name: installs leto default configuration
  template:
    src: leto.yml.j2
    dest: /etc/default/leto.yml
