---
- name: ensures sensible variable are set
  fail:
    msg: "You must define the sensible variables 'vault_olympus_stream_server' and 'vault_slack_webhook' in 'group_vars/vault'"
  when: vault_olympus_stream_server == None

- name: ensures avahi-daemon
  apt:
    name: avahi-daemon
    state: present


- name: installs common utilities
  apt:
    name:
      - tmux
      - emacs-nox
      - vim
      - aptitude
      - cockpit
      - python-is-python3
    state: present
    update_cache: true
