---
- name: ensures sensible variable are set
  fail:
    msg: "You must define the sensible variables 'vault_olympus_stream_server' and 'vault_slack_webhook' in 'group_vars/vault'"
  when: vault_slack_webhook == None or vault_olympus_stream_server == None

- name: ensures avahi-daemon
  apt:
    name: avahi-daemon
    state: latest

- name: installs common utilities
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - tmux
      - emacs
      - vim
      - aptitude
      - cockpit
