---
- name: builds olympus
  shell: |
    cd /home/olympus/olympus
    /usr/local/go/bin/go build
    cd webapp
    yarn install
    yarn build

- name: restarts rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: enables olympus service
  systemd:
    name: olympus
    enabled: yes
    daemon_reload: yes

- name: restarts olympus service
  systemd:
    name: olympus
    state: restarted
