---
- name: restarts rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: enables olympus service
  systemd:
    name: olympus
    enabled: yes
    daemon_reload: yes

- name: restarts olympus service
  systemd:
    name: olympus
    state: restarted
