---

- name: rebuild olympus
  command:
    chdir: /usr/local/src/olympus
    cmd: docker compose build --pull

- name: restart olympus
  command:
    chdir: /usr/local/src/olympus
    cmd: docker compose up -d --remove-orphans
