---

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted

- name: enable olympus service
  systemd:
    name: olympus
    enabled: yes
    daemon_reload: yes

- name: restart olympus service
  systemd:
    name: olympus
    state: restarted
