---

- name: install nfs-utility
  apt:
    name: nfs-kernel-server
    state: present

- name: sets the nfs configuration
  template:
    src: etc_exports.conf.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  notify: "restarts nfs"
