---

- name: installs can-utils
  apt:
    name: can-utils
    state: present

- name: installs slcand@ service template
  copy:
    src: slcand@.service
    dest: /etc/systemd/system/slcand@.service

- name: creates interfaces configuration directory
  file:
    name: /etc/default/slcand
    state: directory
    mode: '0755'

- name: installs interfaces configurations
  template:
    src: device.env
    dest: "/etc/default/slcand/{{item.key}}.env"
  loop: "{{slcan_interfaces | dict2items }}"

- name: enables slcand@ services
  systemd:
    name: "slcand@{{item.key}}.service"
    enabled: yes
    state: started
  loop: "{{slcan_interfaces | dict2items }}"
