---
- name: installs custom fact
  copy:
    src: fort-list-users.fact
    dest: /etc/ansible/facts.d/fort-list-users.fact
    mode: 0755
  register: custom_fact_installed

- name: reloads facts
  setup:
  when: custom_fact_installed.changed

- name: adds default user
  shell: |
    if id -u fort-user > /dev/null
    then
    	exit 0
    fi
    echo -ne "123456\n123456\nDefault user for the FORmicidae Tracker\n\n\n\n\n" | adduser fort-user
    echo "fort-user:123456" | /usr/sbin/chpasswd
  when: '"fort-user" not in ansible_local["fort-list-users"]'


- name: adds default monitor
  when: need_virtual_monitor
  block:
    - name: ensures custom gnome-shell@wayland
      copy:
        dest: /etc/systemd/user/org.gnome.Shell@wayland.service
        force: false
        remote_src: true
        src: /usr/lib/systemd/user/org.gnome.Shell@wayland.service
        owner: root
        mode: 0644
    - name: ensures custom gnome-shell@wayland has virtual monitor
      lineinfile:
        path: /etc/systemd/user/org.gnome.Shell@wayland.service
        regexp: '^ExecStart=/usr/bin/gnome-shell'
        line: ExecStart=/usr/bin/gnome-shell --virtual-monitor 1920x1080
      notify: reboots system



- name: ensure data directory exists
  file:
    path: /data/fort-user
    state: directory
    owner: fort-user
    group: fort-user
    mode: 0755

- name: sets user as default logged in user
  copy:
    src: daemon.conf
    dest: /etc/gdm3/custom.conf
  notify: reboots system
